version: '3.3'

# devo usar root como user e a senha de MYSQL_ROOT_PASSWORD
# para me conectar

services:
  app:
    build: docker
    image: laravel-app
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-blog
      - MYSQL_USER=ntic
      - MYSQL_PASSWORD=ntic_password 
    volumes:
      - db-data:/var/lib/mysql:cached

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  
    

volumes:
  db-data:
